# Generated by Django 5.1.1 on 2024-09-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0003_perfilusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'Terror'), (2, 'Acción'), (3, 'Carreras'), (4, 'Deportes'), (5, 'Supervivencia'), (6, 'Mundo Abierto')]),
        ),
    ]
