# Generated by Django 5.1.1 on 2024-09-16 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0004_alter_juego_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
